#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: 'http://127.0.0.1:5500, *, http://171.241.62.13:5500'
#            allowedHeaders: '*'
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PATCH
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PATCH
            allowCredentials: true
          
