version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=longdq
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql-test:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
